# Spring Semester - Teaching Week 2 w/c 8/2

# Introduction to NumPy 

Learning outcomes:  
- Learn about the NumPy package for scientific computation in Python.
- Learn more about basic types and functions in NumPy
- Learn about arrays in NumPy


**How to read**:
Browse through and evaluate all 'code cells'. This will give you knowledge about what properties are available and 
some examples of what you can do with files and functions etc.  If you need more information, please read through the references below. 

Then do the exercises below and play around and modify or try the different properties I have used here. 

You are **not** expected to memorise everything here. You are always allowed to look at examples and documentation when you solve programming problems, so the most important is to know what is possible.  


## References ##

Recommended reading:
- Learning Scientific Programming..." by C. Hill, Chapter 6.1-
Other sources: 
- https://numpy.org/ (the main website - contains all documentations and introductions etc.)
- https://cs231n.github.io/python-numpy-tutorial/ (a good tutorial on numpy)

## Introduction ##

NumPy is a large package containing efficient and accurate algorithms for scientific programming and in particular it is focussed on numerical linear algebra. The algorithms in this library are mostly written in C, C++ or Fortran, which makes them much faster than a "basic" Python implementation would be. 
NumPy is a part of the more general SciPy package for scientific computation which also includes more general methods for special functions etc.

You will already be familiar with some of the functionality of numpy that was included in pylab. Recall that pylab consisted of selected functions from numpy and matplotlib (which we will discuss in more detail later).

As usual we will only provide a brief overview here. For full and detailed information see the references above (in particular the recommended book). 

## Usage and Installation ##

To use numpy in your code you need to import it before you want to use it. 
A common practice to make your code look "neater" is to write 

`import numpy as np`

This will define `np` as an "alias" for numpy in your worksheet, in other words, instead of typing `numpy.<function_name>` you can write `np.<function_name>`. 
I will adopt this convention in this notebook but it is optional in your own code, you can always just write `import numpy` and call all functions as starting with `numpy`

If get a 'ModuleNotFoundError' when you try to import it this meanst that you first need to install it.
If you use Anaconda numpy should be installed by default - but something could have gone wrong.
To install NumPy see https://numpy.org/install for details or simply do the below:
* Anaconda: go to Environments, select the current environment (probably called 'base (root)'), select 'All' packages, search for 'numpy' and install it.
* Miniconda:  on the command line write `conda install numpy`
* Pip:  on the command line write `pip install numpy` 

## Content of this notebook

1. Arrays and basic datatypes
2. Matrices
3. Element-wise operations
4. Special values
5. Magic squares (an Example)
6. Advanced array manipulation

In [2]:
import numpy as np

## Arrays and basic data types 

The basic datatype in numpy is the `array` object which has type `ndarray` and it has a number of built-in properties, including addition and scalar multiplication (corresponding to vector space properties).

In [3]:
x = np.array([1,2,3])
y = np.array([1.0,1,1])
z = np.array([1,1.1,3+1j])
type(z)

numpy.ndarray

In [4]:
# Addition
print(x+y)
# Multiplication by scalar
print( (1+2j)*x)

[2. 3. 4.]
[1.+2.j 2.+4.j 3.+6.j]


Individual elements in numpy have numerical types which are corresponding to integers, floats and complex numbers etc.

In [5]:
print(type(x[1]))
print(type(y[0]))
print(type(z[1]))

<class 'numpy.int64'>
<class 'numpy.float64'>
<class 'numpy.complex128'>


It is important to note that a numpy array object can only contain elements of the same type so in the above example all elements of y are floats and all elements of z are complex numbers.
Also, when adding arrays of different types all elements are put into the most general type (i.e. according to the principle "an integer is a real number which is also a complex number").
For a list of all common numpy datatypes see Table 6.2 in the book by Hill.

In [6]:
type((x+z)[0])

numpy.complex128

If you need to define a vector with specific datatype you can do it explicitly as

In [7]:
x = np.array([1,2,3],dtype=np.complex128)
print(type(x[0]))

<class 'numpy.complex128'>


## Matrices 
In addition to vectors, we can also represent matrices as multi-dimensional arrays in numpy.
There is also a special matrix class in numpy (which we will see later) but for most purposes arrays are just as good representations of matrices.
Matrices (in either form) can be created using input as a list of lists:

In [10]:
A = np.array([[1,2],[1,1]])
B = np.array([[1,4],[0,1]])
print(A)
# We can add matrices
print(A+B)

[[1 2]
 [1 1]]
[[2 6]
 [1 2]]


Elements of matrices (multi-dimensional arrays) are indexed by using A[m,n] instead of the expected A[m][n]

In [11]:
print(A[0,0])
print(A[0,1])
print(A[1,0])
print(A[1,1])

1
2
1
1


To get the number of rows and columns you can use the `shape` property:

In [12]:
A.shape

(2, 2)

It is possible to create an array of zeros or ones of any 'shape'  (the default type is float but you can specify other types using the 'dtype' keyword argument).

In [14]:
A = np.zeros((3,3), dtype=np.int64)
print(A)
B = np.ones((3,2))
print(B)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


It is also possible to create ranges of elements in numpy in a similar way as we have seen before 

In [17]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In contrast to the built-in `range` function in Python you can also give floating point arguments and it will produce a range up to the right limit

In [18]:
np.arange(0.5,20.2)

array([ 0.5,  1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5,
       11.5, 12.5, 13.5, 14.5, 15.5, 16.5, 17.5, 18.5, 19.5])

You can also specify a floating point step size:

In [19]:
np.arange(0.,10.,np.pi)

array([0.        , 3.14159265, 6.28318531, 9.42477796])

We also encountered the linspace function which produces an array of equally spaced points. 
There are two additional parameters that might be useful:
- `retstep`  - set to True (default False) to return the stepsize
- `endpoint` - set to False to not include the right endpoint (default True)

In [22]:
np.linspace(0,10,10,retstep=True)

(array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
         5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ]),
 1.1111111111111112)

In [21]:
np.linspace(0,10,10,retstep=True,endpoint=False)

(array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), 1.0)

### Initializing an array or matrix from a function

It is possible to define an array directly using a function as follows.
assume that we want to create a 3x3 matrix that contains the signs 1 or -1 alternating in rows and columns: 

In [23]:
def f(i,j):
    return (-1)**(i+j)

In [24]:
np.fromfunction(f,(3,3))

array([[ 1., -1.,  1.],
       [-1.,  1., -1.],
       [ 1., -1.,  1.]])

## Element-wise operations

The functionality for element-wise functions that we used in pylab earlier are all coming from numpy so they can also be used here. 
For example

In [ ]:
np.sin(np.pi*np.array([1,2,2.5]))

It is also possible to compare arrays element-wise:

In [ ]:
np.array([1,2,2.5]) < np.array([1,2,3])

In [ ]:
np.array([1,2,2.5]) == np.array([1,2,3])

In [ ]:
# If we compare with a scalar then this scalar is made to a vector first:
np.array([1,2,3]) > 1

### Example 
As an example let's use numpy arrays and a combination of boolean functions to determine which values between 0 and 100 are congruent to 1 modulo 3 and 2 modulo 5:

I will use the range between 0 and 101 so that element n is the number n (recall that Python indexing starts at 0

In [ ]:
np.arange(0,101)

In [ ]:
np.arange(0,101)[37]

In [ ]:
# Array that indicates which values are congruent to 1 modulo 3
a=(np.arange(0,101) % 3 == 1) 
a

In [ ]:
# Array that indicates which values are congruent to 2 modulo 5
b=(np.arange(0,101) % 5 == 2)
b

In [ ]:
# Array which gives the values congruent to both 1 mod 3 and 2 mod 5
c = a & b 
c

Note that we had to use the special "bitwise" logical operator `&` to be able to compare the arrays element-wise. 
The more natural "a and b" will **not** work. 
As an alternative to `&` we can also simply multiply element-wise since True*True=True and True*False=False and False*False=False when True is interpreted as 1 and False as 0.

In [ ]:
a & b == a*b

We can find out which values are congruent to both 1 mod 3 and 2 mod 5 by finding the nonzero values using the `nonzero` function which returns the indices of all elements that are not zero (this works because False is treated as 0)

In [ ]:
c.nonzero()

So the integers $x$ between 1 and 100 which satisfy $x\equiv 1\pmod{3}$ and $x\equiv 2\pmod{5}$ are precisely 
7,22,37,52,67,82 and 97.

Instead of the nonzero function we could also have produced the matching values using a generator function in Python:

In [ ]:
[x for x in range(101) if c[x]]

### Matrix multiplication
It is important to know that all elementary operations are by default element-wise, including multiplication, so for instance

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [ ]:
# Element-wise multiplication
x*y

In [ ]:
# dot-product
x.dot(y)

This is especially important when it comes to matrices.
To multiply two matrices you need to use the `matmul` or `dot` function:

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,0],[0,1]])
# Element-wise multiplication
A*B

In [ ]:
# matrix multiplication
np.matmul(A,B)

In [ ]:
A.dot(B)

Note that the `dot` as a matrix multiplication is precisely the dot product of two vectors since the "natural" way to multiply two vectors x and y of length d is to treat x as a row vector (i.e. an 1 x d matrix) and y as a column vector (i.e. a d x 1 matrix) and the resulting matrix product is precisely the 1x1 matrix consisting of the dot (or scalar) product. 

## Special values

NumPy have the special values `nan` (not a number) and `inf` (infinity) (and `-inf` for minus infinity) which are used to denote undefined values like 0/0 and infinities like 1/0 or -1/0.

Note that by default numpy will also print out a warning if you try to divide by 0 but this can be configured to be hidden if needed.

In [ ]:
np.array([0,1,-1])/0

There is also a "complex" infinity `inf+infj`:

In [ ]:
np.array([1+1j])/0

To test if a value is infinity you can't use a simple `==` or `!=` since infinities are not comparable. There are instead functions `np.isnan` and `np.isinf` and `np.isfinite`

In [ ]:
a=np.array([0,1,-1])/0

In [ ]:
print(f"{a[0]} is nan: {np.isnan(a[0])}")
print(f"{a[1]} is nan: {np.isnan(a[1])}")
print(f"{a[2]} is nan: {np.isnan(a[2])}")
print(f"{a[0]} is inf: {np.isinf(a[0])}")
print(f"{a[1]} is inf: {np.isinf(a[1])}")
print(f"{a[2]} is inf: {np.isinf(a[2])}")

## Magic Squares

A magic square is an N x N matrix where each row and column and the main diagonal sum to the same value and where the entries consists of the values $1,2,\ldots,N^2$ exactly once. (Note that the sum is actually equal to $N(N^2+1)/2$) (see e.g. https://mathworld.wolfram.com/MagicSquare.html.)
The following outlines an algorithm to create a magic square for an odd $N$:
- Step 1: Start in the middle of the top row and let n=1
- Step 2: Insert n in the current grid position
- Step 3: If $n=N^2$ then we are done so we stop, else increment $n$ by 1. 
- Step 4: Move diagonally up and to the right one step, where we "wrap" the matrix in the sense that if we try to move to the right of the last column we end up in the first column and if we try to move up from the first row we end up in the last row. If this cell is filled we move vertically down one step instead.
- Step 5: Go to Step 2. 

This algorithm can be implemented using numpy as

In [ ]:
def magic_square(N):
    if N % 2 == 0 or N<1:
        raise ValueError("Input must be an odd positive integer!")
    magic_square = np.zeros((N,N),dtype=int)
    # Use i and j to denote the current row and column position
    i = 0
    j = int((N-1)/2)
    n = 1
    while n <= N**2:
        magic_square[i,j] = n
        n += 1
        # Move up one step (or to the bottom row)
        newi = (i-1) % N
        # Move to the right one step (or to the first column)
        newj = (j+1) % N
        if magic_square[newi,newj] != 0:
            # If this matrix element is already set we move vertically down one step
            i = i+1 
        else:
            i,j = newi,newj
    return magic_square

In [ ]:
A=magic_square(3)
A

For such a small matrix it is easy to check by hand that all rows and columns and the diagonal sums to 15. 
for larger matrices there is an exercise below which asks you to write a function to verify whether or not a given matrix is magic.

## Advanced array manipulations and indexing

### Changing shape of an array


In [ ]:
A=np.array([[1,2,3],[4,5,6]])
print(A)

1. `flatten` can be used to put all rows of a matrix into one vector

In [ ]:
A.flatten()

2. `reshape` can be used to convert a matrix from one shape to another:

In [ ]:
A.reshape(3,2) # same as if we had written A = np.array([[1,2],[3,4],[5,6]])

3. `transpose` can be used to transpose a matrix:

In [ ]:
A.transpose()

4. `hstack`, `vstack`, `dstack` are used to "stack" (or join) arrays according to different axes:

In [ ]:
a = np.array([0,0,0,0])
b = np.array([1,1,1,1])
c = np.array([2,2,2,2])

In [ ]:
np.vstack((a,b,c)) # "vertically" - the same as np.array((a,b,c))

In [ ]:
np.hstack((a,b,c)) # 'horizontally" - the same as np.array(list(a)+list(b)+list(c))

In [ ]:
np.dstack((a,b,c)) # "in a third direction..." - the same as np.array(list(zip(a,b,c)))

In [ ]:
np.dsplit(np.dstack((a,b,c)),3)

5. The "inverse" operation of splitting an array is done by `hsplit` (split in columns), `vsplit` (split with respect to rows) and `dsplit` (split in depth). Note that the splitting must be done in equal parts.

In [ ]:
# hsplit works on arrays of dimension 1
a = np.arange(10)
print(a)
print(np.hsplit(a,2))
print(np.hsplit(a,5))

In [ ]:
np.hsplit(a,3) # raises an error

In [ ]:
# vsplit works on arays of dimension 2
A = np.array([[1,2],[4,5]])
print(A)
print(np.vsplit(A,2))

In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(A)
print(np.vsplit(A,2))

In [ ]:
# And dsplit works only on arrays of dimension 3 and higher.
# This is not very common to need but as an example we can split the array we stacked earlier
a = np.array([0,0,0,0])
b = np.array([1,1,1,1])
c = np.array([2,2,2,2])
print(np.dstack((a,b,c)))
np.dsplit(np.dstack((a,b,c)),3)

### Adding rows and columns
It is easy to see how to add a row to a matrix using `vstack`

In [ ]:
A = np.array([[1,1,1],[2,2,2],[3,3,3]])
b = np.array([4,4,4])
print(np.vstack((A,b)))

To add a column we can similarly use `hstack` but since a single array has the shape of a row vector it can't be added directly:

In [ ]:
c = np.array([1,2,3])

In [ ]:
np.hstack((A,c))

We need to first use either `reshape` or `hsplit` to make sure that the array has the correct column shape:

In [ ]:
np.hstack((A,c.reshape(3,1)))

### Advanced array indexing 

Arrays can be indexed in the same way as lists in Python:

In [25]:
print(A)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [37]:
A[1,:] # second row

array([0, 0, 0])

In [39]:
A[1:3,1:3] # right lower sub-matrix

array([[0, 0],
       [0, 0]])

It is also possible to use more advanced indexing, for instance we can give a list as index:

In [ ]:
a = np.arange(10,100)
print(a)

In [ ]:
a[[1,2,8]]

Or we can use a list of booleans as indices. Then the resulting array consists of values where the boolean is True

In [ ]:
a = np.arange(0,4)
print(a)
print(a[[True,False,False,True]])

**Example**

Take the list of integers from 1 to 100 and set every element which is congruent to 1 mod 3 and 2 mod 5 to zero:

In [ ]:
a = np.arange(1,101)
print(a)

In [ ]:
b = (a % 3 == 1) & (a % 5 == 2)
print(b)

In [ ]:
a[b]

In [ ]:
a[b]=0 # Set all values to 0 where the indexes matches b
print(a)

## Exercises ##

**Exercise 1**
Create a 4x4 matrix $A=(a_{ij})$ where the entries are given by 
$$a_{ij}=\sin((2i+1)\pi/2)\cos(j\pi), \; 1\le i,j\le 4$$

As usual matrix entries start with $a_{11}$ in top left corner and row and column index increases to the right and down. 

**Exercise 2**
(a). Create the following 4 x 4 matrix, $A$, containing the integers from 1 to 16 using `np.arange` and `np.reshape`
$$
A=\left(\begin{array}{rrrr}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12 \\
13 & 14 & 15 & 16
\end{array}\right)
$$
(b). Use indexing to select the submatrix 
$$
\left(\begin{array}{rr}
7 & 8 \\
15 & 16
\end{array}\right)
$$

**Exercise 3** Write a function `filter_array` that takes an array as input and returns an array consisting of the values from the input array  that have values between 0 and 1 (inclusive). for example `filter_array(np.array([1,-1,0.1,4.]))=[1,0.1]

In [ ]:
def filter_array(a):
    # YOUR CODE HERE

You can use the following test to make sure that your function returns the correct value for the input np.array([1,-1,0.1,4.]
Question: can you explain why I have written the test as `assert_true( all( x == y ) )` instead of simply `assert_equal(x,y)` ?

In [ ]:
from nose.tools import assert_true
assert_true( all( filter_array(np.array([1,-1,0.1,4.])) == [1,0.1])) 

**Exercise 4** Write a function `is_monotone_increasing` that takes an array as input and return True if the array is monotonically increasing and otherwise returns False. 
Hint: `np.diff`. returns the difference between consecutive elements of a sequence, e.g. `np.diff([1,2,3,4,5])=array([1, 1, 1, 1])`

In [ ]:
def is_monotone_increasing(a):
    # YOUR CODE HERE

You can use the following test to make sure that your function returns the correct value for the input.

In [ ]:
from nose.tools import assert_true,assert_false
assert_true(is_monotone_increasing(np.array([1,2,3,4])))
assert_true(is_monotone_increasing(np.array([1,2,2,3,4])))
assert_false(is_monotone_increasing(np.array([1,3,2,3,4])))                              

**Exercise 3.** Write a function using numpy and the `sum` function for arrays (look up the built-in help "A.sum?") which checks if a given matrix is a magic square or not.   

In this case you can test your solution using the function defined above to create magic squares and compare with some non-magic square matrices.  

In [ ]:
def is_magic_square(A):
    r"""
    Check if A is a magic square or not.
    """
    # YOUR CODE HERE 